# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
project 'SuperIDRN-Demo.xcodeproj'

target 'SuperIDRN-Demo' do

pod 'SuperIDRN', :path => '../'

pod 'React', :path => '../../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
]

end
